services:
  - type: web
    name: email-client
    env: static
    buildCommand: cd apps/client && npm install && npm run build
    staticPublishPath: apps/client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
